import { ApiProperty } from '@nestjs/swagger';
import type { PermissionKey } from '@prisma/client';
import { IsEnum } from 'class-validator';

const PERMISSION_KEYS = [
  'USER_VIEW',
  'USER_EDIT',
  'BUILDING_VIEW',
  'BUILDING_EDIT',
  'MARKETPLACE_REVIEW',
  'MARKETPLACE_APPROVE',
  'FINANCE_VIEW',
  'FINANCE_REFUND',
  'AUDIT_VIEW',
  'SYSTEM_SETTINGS',
  'FEATURE_FLAGS',
  'SUBSCRIPTION_VIEW',
  'SUBSCRIPTION_MANAGE',
  'BUILDING_VERIFICATION_VIEW',
  'BUILDING_VERIFICATION_MANAGE',
  'MANAGER_VERIFICATION_VIEW',
  'MANAGER_VERIFICATION_MANAGE',
  'FRAUD_VIEW',
  'FRAUD_MANAGE',
  'SUPPORT_VIEW',
  'SUPPORT_MANAGE',
  'COMPLIANCE_VIEW',
  'COMPLIANCE_MANAGE',
  'LEGAL_HOLD_MANAGE',
  'PERSON_ACCESS_VIEW',
  'PERSON_ACCESS_MANAGE',
  'NOTIFICATION_TEMPLATE_VIEW',
  'NOTIFICATION_TEMPLATE_MANAGE',
  'SCHEDULER_TRIGGER',
  'GAMIFICATION_ANALYTICS_VIEW',
] as const;

/** 21_ADRs > ADR-099 §6 — `POST /backoffice/rbac/roles/:roleId/permissions`. */
export class GrantPermissionDto {
  @ApiProperty({ enum: PERMISSION_KEYS })
  @IsEnum(PERMISSION_KEYS)
  permissionKey!: PermissionKey;
}
