import { LocationNames } from './countries';

export interface CityOption {
  code: string;
  provinceCode: string;
  names: LocationNames;
}

/**
 * Practical (not just provincial-capital) city dataset for all 31 Iran
 * provinces (Building Setup Refinement Phase 2). ~260 cities total — a
 * curated, reasonably-complete list drawn from general geographic
 * reference knowledge, NOT an exhaustive official gazetteer; smaller
 * towns can be added later without touching validation logic.
 *
 * City identity is deliberately scoped to its province: `code` is
 * `<provinceCode>-<CITY_SLUG>` (e.g. `IR-TEHRAN-TEHRAN`), never the bare
 * city name — city names repeat across provinces, so the bare name is
 * never used as an identifier anywhere in this dataset or its validators.
 * Like province codes, these are VielHome-internal identifiers, not an
 * official standard.
 *
 * `names.tr` — LOCALIZATION QUALITY NOTE: a verified, individually
 * researched Turkish exonym does not reliably exist for most of these
 * ~260 towns. Rather than leave `tr` equal to `en` (an English copy
 * silently mislabeled as "Turkish"), city Turkish names are produced
 * by a deterministic transliteration of the English spelling into
 * Turkish orthography ("sh"->"ş", "kh"->"h", "ch"->"ç", "gh"->"ğ",
 * "q"->"k", "j"->"c", "w"->"v"), with the ~13 provincial-capital
 * cities that share their province's name (e.g. Tehran, Isfahan, Kerman)
 * upgraded to match that province's hand-curated Turkish name. This is a
 * disclosed, deliberate choice — Latin-script transliteration standing
 * in for individually curated exonyms — NOT a claim that every city has
 * a verified distinct Turkish name. Where the English spelling contains
 * none of the substituted digraphs (roughly half of the list), `tr`
 * coincides with `en`; that is an inherent, disclosed limitation of the
 * mechanical approach, not an oversight.
 */
export const IRAN_CITIES: readonly CityOption[] = [
  { code: 'IR-TEHRAN-TEHRAN', provinceCode: 'IR-TEHRAN', names: { en: 'Tehran', fa: 'تهران', tr: 'Tahran' } },
  { code: 'IR-TEHRAN-REY', provinceCode: 'IR-TEHRAN', names: { en: 'Rey', fa: 'ری', tr: 'Rey' } },
  { code: 'IR-TEHRAN-SHEMIRANAT', provinceCode: 'IR-TEHRAN', names: { en: 'Shemiranat', fa: 'شمیرانات', tr: 'Şemiranat' } },
  { code: 'IR-TEHRAN-ESLAMSHAHR', provinceCode: 'IR-TEHRAN', names: { en: 'Eslamshahr', fa: 'اسلامشهر', tr: 'Eslamşahr' } },
  { code: 'IR-TEHRAN-SHAHRIAR', provinceCode: 'IR-TEHRAN', names: { en: 'Shahriar', fa: 'شهریار', tr: 'Şahriar' } },
  { code: 'IR-TEHRAN-ROBAT_KARIM', provinceCode: 'IR-TEHRAN', names: { en: 'Robat Karim', fa: 'رباط کریم', tr: 'Robat Karim' } },
  { code: 'IR-TEHRAN-PAKDASHT', provinceCode: 'IR-TEHRAN', names: { en: 'Pakdasht', fa: 'پاکدشت', tr: 'Pakdaşt' } },
  { code: 'IR-TEHRAN-VARAMIN', provinceCode: 'IR-TEHRAN', names: { en: 'Varamin', fa: 'ورامین', tr: 'Varamin' } },
  { code: 'IR-TEHRAN-DAMAVAND', provinceCode: 'IR-TEHRAN', names: { en: 'Damavand', fa: 'دماوند', tr: 'Damavand' } },
  { code: 'IR-TEHRAN-FIRUZKUH', provinceCode: 'IR-TEHRAN', names: { en: 'Firuzkuh', fa: 'فیروزکوه', tr: 'Firuzkuh' } },
  { code: 'IR-TEHRAN-PARDIS', provinceCode: 'IR-TEHRAN', names: { en: 'Pardis', fa: 'پردیس', tr: 'Pardis' } },
  { code: 'IR-TEHRAN-MALARD', provinceCode: 'IR-TEHRAN', names: { en: 'Malard', fa: 'ملارد', tr: 'Malard' } },
  { code: 'IR-TEHRAN-QODS', provinceCode: 'IR-TEHRAN', names: { en: 'Qods', fa: 'قدس', tr: 'Kods' } },
  { code: 'IR-TEHRAN-BAHARESTAN', provinceCode: 'IR-TEHRAN', names: { en: 'Baharestan', fa: 'بهارستان', tr: 'Baharestan' } },
  { code: 'IR-ALBORZ-KARAJ', provinceCode: 'IR-ALBORZ', names: { en: 'Karaj', fa: 'کرج', tr: 'Karac' } },
  { code: 'IR-ALBORZ-FARDIS', provinceCode: 'IR-ALBORZ', names: { en: 'Fardis', fa: 'فردیس', tr: 'Fardis' } },
  { code: 'IR-ALBORZ-NAZARABAD', provinceCode: 'IR-ALBORZ', names: { en: 'Nazarabad', fa: 'نظرآباد', tr: 'Nazarabad' } },
  { code: 'IR-ALBORZ-HASHTGERD', provinceCode: 'IR-ALBORZ', names: { en: 'Hashtgerd', fa: 'هشتگرد', tr: 'Haştgerd' } },
  { code: 'IR-ALBORZ-ESHTEHARD', provinceCode: 'IR-ALBORZ', names: { en: 'Eshtehard', fa: 'اشتهارد', tr: 'Eştehard' } },
  { code: 'IR-ALBORZ-TALEQAN', provinceCode: 'IR-ALBORZ', names: { en: 'Taleqan', fa: 'طالقان', tr: 'Talekan' } },
  { code: 'IR-ALBORZ-MAHDASHT', provinceCode: 'IR-ALBORZ', names: { en: 'Mahdasht', fa: 'محمدشهر', tr: 'Mahdaşt' } },
  { code: 'IR-ISFAHAN-ISFAHAN', provinceCode: 'IR-ISFAHAN', names: { en: 'Isfahan', fa: 'اصفهان', tr: 'İsfahan' } },
  { code: 'IR-ISFAHAN-KASHAN', provinceCode: 'IR-ISFAHAN', names: { en: 'Kashan', fa: 'کاشان', tr: 'Kaşan' } },
  { code: 'IR-ISFAHAN-NAJAFABAD', provinceCode: 'IR-ISFAHAN', names: { en: 'Najafabad', fa: 'نجف‌آباد', tr: 'Nacafabad' } },
  { code: 'IR-ISFAHAN-KHOMEINISHAHR', provinceCode: 'IR-ISFAHAN', names: { en: 'Khomeinishahr', fa: 'خمینی‌شهر', tr: 'Homeinişahr' } },
  { code: 'IR-ISFAHAN-SHAHIN_SHAHR', provinceCode: 'IR-ISFAHAN', names: { en: 'Shahin Shahr', fa: 'شاهین‌شهر', tr: 'Şahin Şahr' } },
  { code: 'IR-ISFAHAN-MOBARAKEH', provinceCode: 'IR-ISFAHAN', names: { en: 'Mobarakeh', fa: 'مبارکه', tr: 'Mobarakeh' } },
  { code: 'IR-ISFAHAN-FALAVARJAN', provinceCode: 'IR-ISFAHAN', names: { en: 'Falavarjan', fa: 'فلاورجان', tr: 'Falavarcan' } },
  { code: 'IR-ISFAHAN-GOLPAYEGAN', provinceCode: 'IR-ISFAHAN', names: { en: 'Golpayegan', fa: 'گلپایگان', tr: 'Golpayegan' } },
  { code: 'IR-ISFAHAN-NAEIN', provinceCode: 'IR-ISFAHAN', names: { en: 'Naein', fa: 'نائین', tr: 'Naein' } },
  { code: 'IR-ISFAHAN-ARDESTAN', provinceCode: 'IR-ISFAHAN', names: { en: 'Ardestan', fa: 'اردستان', tr: 'Ardestan' } },
  { code: 'IR-ISFAHAN-SEMIROM', provinceCode: 'IR-ISFAHAN', names: { en: 'Semirom', fa: 'سمیرم', tr: 'Semirom' } },
  { code: 'IR-ISFAHAN-FEREYDUNSHAHR', provinceCode: 'IR-ISFAHAN', names: { en: 'Fereydunshahr', fa: 'فریدون‌شهر', tr: 'Fereydunşahr' } },
  { code: 'IR-ISFAHAN-ZARRINSHAHR', provinceCode: 'IR-ISFAHAN', names: { en: 'Zarrinshahr', fa: 'زرین‌شهر', tr: 'Zarrinşahr' } },
  { code: 'IR-ISFAHAN-TIRAN', provinceCode: 'IR-ISFAHAN', names: { en: 'Tiran', fa: 'تیران', tr: 'Tiran' } },
  { code: 'IR-FARS-SHIRAZ', provinceCode: 'IR-FARS', names: { en: 'Shiraz', fa: 'شیراز', tr: 'Şiraz' } },
  { code: 'IR-FARS-MARVDASHT', provinceCode: 'IR-FARS', names: { en: 'Marvdasht', fa: 'مرودشت', tr: 'Marvdaşt' } },
  { code: 'IR-FARS-JAHROM', provinceCode: 'IR-FARS', names: { en: 'Jahrom', fa: 'جهرم', tr: 'Cahrom' } },
  { code: 'IR-FARS-KAZERUN', provinceCode: 'IR-FARS', names: { en: 'Kazerun', fa: 'کازرون', tr: 'Kazerun' } },
  { code: 'IR-FARS-FASA', provinceCode: 'IR-FARS', names: { en: 'Fasa', fa: 'فسا', tr: 'Fasa' } },
  { code: 'IR-FARS-LAR', provinceCode: 'IR-FARS', names: { en: 'Lar', fa: 'لار', tr: 'Lar' } },
  { code: 'IR-FARS-DARAB', provinceCode: 'IR-FARS', names: { en: 'Darab', fa: 'داراب', tr: 'Darab' } },
  { code: 'IR-FARS-FIRUZABAD', provinceCode: 'IR-FARS', names: { en: 'Firuzabad', fa: 'فیروزآباد', tr: 'Firuzabad' } },
  { code: 'IR-FARS-NEYRIZ', provinceCode: 'IR-FARS', names: { en: 'Neyriz', fa: 'نی‌ریز', tr: 'Neyriz' } },
  { code: 'IR-FARS-ABADEH', provinceCode: 'IR-FARS', names: { en: 'Abadeh', fa: 'آباده', tr: 'Abadeh' } },
  { code: 'IR-FARS-EQLID', provinceCode: 'IR-FARS', names: { en: 'Eqlid', fa: 'اقلید', tr: 'Eklid' } },
  { code: 'IR-FARS-ESTAHBAN', provinceCode: 'IR-FARS', names: { en: 'Estahban', fa: 'استهبان', tr: 'Estahban' } },
  { code: 'IR-FARS-ZARGHAN', provinceCode: 'IR-FARS', names: { en: 'Zarghan', fa: 'زرقان', tr: 'Zarğan' } },
  { code: 'IR-RAZAVI_KHORASAN-MASHHAD', provinceCode: 'IR-RAZAVI_KHORASAN', names: { en: 'Mashhad', fa: 'مشهد', tr: 'Maşhad' } },
  { code: 'IR-RAZAVI_KHORASAN-NEYSHABUR', provinceCode: 'IR-RAZAVI_KHORASAN', names: { en: 'Neyshabur', fa: 'نیشابور', tr: 'Neyşabur' } },
  { code: 'IR-RAZAVI_KHORASAN-SABZEVAR', provinceCode: 'IR-RAZAVI_KHORASAN', names: { en: 'Sabzevar', fa: 'سبزوار', tr: 'Sabzevar' } },
  { code: 'IR-RAZAVI_KHORASAN-TORBAT_E_HEYDARIEH', provinceCode: 'IR-RAZAVI_KHORASAN', names: { en: 'Torbat-e Heydarieh', fa: 'تربت حیدریه', tr: 'Torbat-e Heydarieh' } },
  { code: 'IR-RAZAVI_KHORASAN-QUCHAN', provinceCode: 'IR-RAZAVI_KHORASAN', names: { en: 'Quchan', fa: 'قوچان', tr: 'Kuçan' } },
  { code: 'IR-RAZAVI_KHORASAN-KASHMAR', provinceCode: 'IR-RAZAVI_KHORASAN', names: { en: 'Kashmar', fa: 'کاشمر', tr: 'Kaşmar' } },
  { code: 'IR-RAZAVI_KHORASAN-GONABAD', provinceCode: 'IR-RAZAVI_KHORASAN', names: { en: 'Gonabad', fa: 'گناباد', tr: 'Gonabad' } },
  { code: 'IR-RAZAVI_KHORASAN-TORBAT_E_JAM', provinceCode: 'IR-RAZAVI_KHORASAN', names: { en: 'Torbat-e Jam', fa: 'تربت جام', tr: 'Torbat-e Cam' } },
  { code: 'IR-RAZAVI_KHORASAN-CHENARAN', provinceCode: 'IR-RAZAVI_KHORASAN', names: { en: 'Chenaran', fa: 'چناران', tr: 'Çenaran' } },
  { code: 'IR-RAZAVI_KHORASAN-FARIMAN', provinceCode: 'IR-RAZAVI_KHORASAN', names: { en: 'Fariman', fa: 'فریمان', tr: 'Fariman' } },
  { code: 'IR-RAZAVI_KHORASAN-TAYBAD', provinceCode: 'IR-RAZAVI_KHORASAN', names: { en: 'Taybad', fa: 'تایباد', tr: 'Taybad' } },
  { code: 'IR-RAZAVI_KHORASAN-SARAKHS', provinceCode: 'IR-RAZAVI_KHORASAN', names: { en: 'Sarakhs', fa: 'سرخس', tr: 'Sarahs' } },
  { code: 'IR-RAZAVI_KHORASAN-BARDASKAN', provinceCode: 'IR-RAZAVI_KHORASAN', names: { en: 'Bardaskan', fa: 'بردسکن', tr: 'Bardaskan' } },
  { code: 'IR-NORTH_KHORASAN-BOJNORD', provinceCode: 'IR-NORTH_KHORASAN', names: { en: 'Bojnord', fa: 'بجنورد', tr: 'Bocnord' } },
  { code: 'IR-NORTH_KHORASAN-SHIRVAN', provinceCode: 'IR-NORTH_KHORASAN', names: { en: 'Shirvan', fa: 'شیروان', tr: 'Şirvan' } },
  { code: 'IR-NORTH_KHORASAN-ESFARAYEN', provinceCode: 'IR-NORTH_KHORASAN', names: { en: 'Esfarayen', fa: 'اسفراین', tr: 'Esfarayen' } },
  { code: 'IR-NORTH_KHORASAN-FAROOJ', provinceCode: 'IR-NORTH_KHORASAN', names: { en: 'Farooj', fa: 'فاروج', tr: 'Farooc' } },
  { code: 'IR-NORTH_KHORASAN-JAJARM', provinceCode: 'IR-NORTH_KHORASAN', names: { en: 'Jajarm', fa: 'جاجرم', tr: 'Cacarm' } },
  { code: 'IR-NORTH_KHORASAN-ASHKHANEH', provinceCode: 'IR-NORTH_KHORASAN', names: { en: 'Ashkhaneh', fa: 'آشخانه', tr: 'Aşhaneh' } },
  { code: 'IR-NORTH_KHORASAN-RAZ', provinceCode: 'IR-NORTH_KHORASAN', names: { en: 'Raz', fa: 'راز', tr: 'Raz' } },
  { code: 'IR-SOUTH_KHORASAN-BIRJAND', provinceCode: 'IR-SOUTH_KHORASAN', names: { en: 'Birjand', fa: 'بیرجند', tr: 'Bircand' } },
  { code: 'IR-SOUTH_KHORASAN-FERDOWS', provinceCode: 'IR-SOUTH_KHORASAN', names: { en: 'Ferdows', fa: 'فردوس', tr: 'Ferdovs' } },
  { code: 'IR-SOUTH_KHORASAN-QAEN', provinceCode: 'IR-SOUTH_KHORASAN', names: { en: 'Qaen', fa: 'قائن', tr: 'Kaen' } },
  { code: 'IR-SOUTH_KHORASAN-NEHBANDAN', provinceCode: 'IR-SOUTH_KHORASAN', names: { en: 'Nehbandan', fa: 'نهبندان', tr: 'Nehbandan' } },
  { code: 'IR-SOUTH_KHORASAN-TABAS', provinceCode: 'IR-SOUTH_KHORASAN', names: { en: 'Tabas', fa: 'طبس', tr: 'Tabas' } },
  { code: 'IR-SOUTH_KHORASAN-SARBISHEH', provinceCode: 'IR-SOUTH_KHORASAN', names: { en: 'Sarbisheh', fa: 'سربیشه', tr: 'Sarbişeh' } },
  { code: 'IR-SOUTH_KHORASAN-BOSHRUYEH', provinceCode: 'IR-SOUTH_KHORASAN', names: { en: 'Boshruyeh', fa: 'بشرویه', tr: 'Boşruyeh' } },
  { code: 'IR-EAST_AZERBAIJAN-TABRIZ', provinceCode: 'IR-EAST_AZERBAIJAN', names: { en: 'Tabriz', fa: 'تبریز', tr: 'Tabriz' } },
  { code: 'IR-EAST_AZERBAIJAN-MARAGHEH', provinceCode: 'IR-EAST_AZERBAIJAN', names: { en: 'Maragheh', fa: 'مراغه', tr: 'Marağeh' } },
  { code: 'IR-EAST_AZERBAIJAN-MARAND', provinceCode: 'IR-EAST_AZERBAIJAN', names: { en: 'Marand', fa: 'مرند', tr: 'Marand' } },
  { code: 'IR-EAST_AZERBAIJAN-MIANEH', provinceCode: 'IR-EAST_AZERBAIJAN', names: { en: 'Mianeh', fa: 'میانه', tr: 'Mianeh' } },
  { code: 'IR-EAST_AZERBAIJAN-AHAR', provinceCode: 'IR-EAST_AZERBAIJAN', names: { en: 'Ahar', fa: 'اهر', tr: 'Ahar' } },
  { code: 'IR-EAST_AZERBAIJAN-SARAB', provinceCode: 'IR-EAST_AZERBAIJAN', names: { en: 'Sarab', fa: 'سراب', tr: 'Sarab' } },
  { code: 'IR-EAST_AZERBAIJAN-BONAB', provinceCode: 'IR-EAST_AZERBAIJAN', names: { en: 'Bonab', fa: 'بناب', tr: 'Bonab' } },
  { code: 'IR-EAST_AZERBAIJAN-SHABESTAR', provinceCode: 'IR-EAST_AZERBAIJAN', names: { en: 'Shabestar', fa: 'شبستر', tr: 'Şabestar' } },
  { code: 'IR-EAST_AZERBAIJAN-JOLFA', provinceCode: 'IR-EAST_AZERBAIJAN', names: { en: 'Jolfa', fa: 'جلفا', tr: 'Colfa' } },
  { code: 'IR-EAST_AZERBAIJAN-HASHTRUD', provinceCode: 'IR-EAST_AZERBAIJAN', names: { en: 'Hashtrud', fa: 'هشترود', tr: 'Haştrud' } },
  { code: 'IR-WEST_AZERBAIJAN-URMIA', provinceCode: 'IR-WEST_AZERBAIJAN', names: { en: 'Urmia', fa: 'ارومیه', tr: 'Urmia' } },
  { code: 'IR-WEST_AZERBAIJAN-KHOY', provinceCode: 'IR-WEST_AZERBAIJAN', names: { en: 'Khoy', fa: 'خوی', tr: 'Hoy' } },
  { code: 'IR-WEST_AZERBAIJAN-MAHABAD', provinceCode: 'IR-WEST_AZERBAIJAN', names: { en: 'Mahabad', fa: 'مهاباد', tr: 'Mahabad' } },
  { code: 'IR-WEST_AZERBAIJAN-MIANDOAB', provinceCode: 'IR-WEST_AZERBAIJAN', names: { en: 'Miandoab', fa: 'میاندوآب', tr: 'Miandoab' } },
  { code: 'IR-WEST_AZERBAIJAN-BUKAN', provinceCode: 'IR-WEST_AZERBAIJAN', names: { en: 'Bukan', fa: 'بوکان', tr: 'Bukan' } },
  { code: 'IR-WEST_AZERBAIJAN-SALMAS', provinceCode: 'IR-WEST_AZERBAIJAN', names: { en: 'Salmas', fa: 'سلماس', tr: 'Salmas' } },
  { code: 'IR-WEST_AZERBAIJAN-PIRANSHAHR', provinceCode: 'IR-WEST_AZERBAIJAN', names: { en: 'Piranshahr', fa: 'پیرانشهر', tr: 'Piranşahr' } },
  { code: 'IR-WEST_AZERBAIJAN-NAQADEH', provinceCode: 'IR-WEST_AZERBAIJAN', names: { en: 'Naqadeh', fa: 'نقده', tr: 'Nakadeh' } },
  { code: 'IR-WEST_AZERBAIJAN-SARDASHT', provinceCode: 'IR-WEST_AZERBAIJAN', names: { en: 'Sardasht', fa: 'سردشت', tr: 'Sardaşt' } },
  { code: 'IR-ARDABIL-ARDABIL', provinceCode: 'IR-ARDABIL', names: { en: 'Ardabil', fa: 'اردبیل', tr: 'Erdebil' } },
  { code: 'IR-ARDABIL-PARSABAD', provinceCode: 'IR-ARDABIL', names: { en: 'Parsabad', fa: 'پارس‌آباد', tr: 'Parsabad' } },
  { code: 'IR-ARDABIL-MESHGIN_SHAHR', provinceCode: 'IR-ARDABIL', names: { en: 'Meshgin Shahr', fa: 'مشگین‌شهر', tr: 'Meşgin Şahr' } },
  { code: 'IR-ARDABIL-KHALKHAL', provinceCode: 'IR-ARDABIL', names: { en: 'Khalkhal', fa: 'خلخال', tr: 'Halhal' } },
  { code: 'IR-ARDABIL-GERMI', provinceCode: 'IR-ARDABIL', names: { en: 'Germi', fa: 'گرمی', tr: 'Germi' } },
  { code: 'IR-ARDABIL-NIR', provinceCode: 'IR-ARDABIL', names: { en: 'Nir', fa: 'نیر', tr: 'Nir' } },
  { code: 'IR-ARDABIL-BILESUVAR', provinceCode: 'IR-ARDABIL', names: { en: 'Bilesuvar', fa: 'بیله‌سوار', tr: 'Bilesuvar' } },
  { code: 'IR-KERMAN-KERMAN', provinceCode: 'IR-KERMAN', names: { en: 'Kerman', fa: 'کرمان', tr: 'Kirman' } },
  { code: 'IR-KERMAN-RAFSANJAN', provinceCode: 'IR-KERMAN', names: { en: 'Rafsanjan', fa: 'رفسنجان', tr: 'Rafsancan' } },
  { code: 'IR-KERMAN-JIROFT', provinceCode: 'IR-KERMAN', names: { en: 'Jiroft', fa: 'جیرفت', tr: 'Ciroft' } },
  { code: 'IR-KERMAN-SIRJAN', provinceCode: 'IR-KERMAN', names: { en: 'Sirjan', fa: 'سیرجان', tr: 'Sircan' } },
  { code: 'IR-KERMAN-ZARAND', provinceCode: 'IR-KERMAN', names: { en: 'Zarand', fa: 'زرند', tr: 'Zarand' } },
  { code: 'IR-KERMAN-BAM', provinceCode: 'IR-KERMAN', names: { en: 'Bam', fa: 'بم', tr: 'Bam' } },
  { code: 'IR-KERMAN-SHAHR_E_BABAK', provinceCode: 'IR-KERMAN', names: { en: 'Shahr-e Babak', fa: 'شهر بابک', tr: 'Şahr-e Babak' } },
  { code: 'IR-KERMAN-KAHNOOJ', provinceCode: 'IR-KERMAN', names: { en: 'Kahnooj', fa: 'کهنوج', tr: 'Kahnooc' } },
  { code: 'IR-KERMAN-BARDSIR', provinceCode: 'IR-KERMAN', names: { en: 'Bardsir', fa: 'بردسیر', tr: 'Bardsir' } },
  { code: 'IR-KHUZESTAN-AHVAZ', provinceCode: 'IR-KHUZESTAN', names: { en: 'Ahvaz', fa: 'اهواز', tr: 'Ahvaz' } },
  { code: 'IR-KHUZESTAN-ABADAN', provinceCode: 'IR-KHUZESTAN', names: { en: 'Abadan', fa: 'آبادان', tr: 'Abadan' } },
  { code: 'IR-KHUZESTAN-KHORRAMSHAHR', provinceCode: 'IR-KHUZESTAN', names: { en: 'Khorramshahr', fa: 'خرمشهر', tr: 'Horramşahr' } },
  { code: 'IR-KHUZESTAN-DEZFUL', provinceCode: 'IR-KHUZESTAN', names: { en: 'Dezful', fa: 'دزفول', tr: 'Dezful' } },
  { code: 'IR-KHUZESTAN-ANDIMESHK', provinceCode: 'IR-KHUZESTAN', names: { en: 'Andimeshk', fa: 'اندیمشک', tr: 'Andimeşk' } },
  { code: 'IR-KHUZESTAN-BEHBAHAN', provinceCode: 'IR-KHUZESTAN', names: { en: 'Behbahan', fa: 'بهبهان', tr: 'Behbahan' } },
  { code: 'IR-KHUZESTAN-MASJED_SOLEYMAN', provinceCode: 'IR-KHUZESTAN', names: { en: 'Masjed Soleyman', fa: 'مسجدسلیمان', tr: 'Masced Soleyman' } },
  { code: 'IR-KHUZESTAN-SHUSHTAR', provinceCode: 'IR-KHUZESTAN', names: { en: 'Shushtar', fa: 'شوشتر', tr: 'Şuştar' } },
  { code: 'IR-KHUZESTAN-IZEH', provinceCode: 'IR-KHUZESTAN', names: { en: 'Izeh', fa: 'ایذه', tr: 'Izeh' } },
  { code: 'IR-KHUZESTAN-RAMHORMOZ', provinceCode: 'IR-KHUZESTAN', names: { en: 'Ramhormoz', fa: 'رامهرمز', tr: 'Ramhormoz' } },
  { code: 'IR-KHUZESTAN-SHADEGAN', provinceCode: 'IR-KHUZESTAN', names: { en: 'Shadegan', fa: 'شادگان', tr: 'Şadegan' } },
  { code: 'IR-KHUZESTAN-HAMIDIEH', provinceCode: 'IR-KHUZESTAN', names: { en: 'Hamidieh', fa: 'حمیدیه', tr: 'Hamidieh' } },
  { code: 'IR-KERMANSHAH-KERMANSHAH', provinceCode: 'IR-KERMANSHAH', names: { en: 'Kermanshah', fa: 'کرمانشاه', tr: 'Kirmanşah' } },
  { code: 'IR-KERMANSHAH-ISLAMABAD_E_GHARB', provinceCode: 'IR-KERMANSHAH', names: { en: 'Islamabad-e Gharb', fa: 'اسلام‌آباد غرب', tr: 'Islamabad-e Ğarb' } },
  { code: 'IR-KERMANSHAH-SONQOR', provinceCode: 'IR-KERMANSHAH', names: { en: 'Sonqor', fa: 'سنقر', tr: 'Sonkor' } },
  { code: 'IR-KERMANSHAH-SAHNEH', provinceCode: 'IR-KERMANSHAH', names: { en: 'Sahneh', fa: 'صحنه', tr: 'Sahneh' } },
  { code: 'IR-KERMANSHAH-HARSIN', provinceCode: 'IR-KERMANSHAH', names: { en: 'Harsin', fa: 'هرسین', tr: 'Harsin' } },
  { code: 'IR-KERMANSHAH-JAVANRUD', provinceCode: 'IR-KERMANSHAH', names: { en: 'Javanrud', fa: 'جوانرود', tr: 'Cavanrud' } },
  { code: 'IR-KERMANSHAH-PAVEH', provinceCode: 'IR-KERMANSHAH', names: { en: 'Paveh', fa: 'پاوه', tr: 'Paveh' } },
  { code: 'IR-KERMANSHAH-KANGAVAR', provinceCode: 'IR-KERMANSHAH', names: { en: 'Kangavar', fa: 'کنگاور', tr: 'Kangavar' } },
  { code: 'IR-KERMANSHAH-RAVANSAR', provinceCode: 'IR-KERMANSHAH', names: { en: 'Ravansar', fa: 'روانسر', tr: 'Ravansar' } },
  { code: 'IR-KURDISTAN-SANANDAJ', provinceCode: 'IR-KURDISTAN', names: { en: 'Sanandaj', fa: 'سنندج', tr: 'Sanandac' } },
  { code: 'IR-KURDISTAN-SAQQEZ', provinceCode: 'IR-KURDISTAN', names: { en: 'Saqqez', fa: 'سقز', tr: 'Sakkez' } },
  { code: 'IR-KURDISTAN-MARIVAN', provinceCode: 'IR-KURDISTAN', names: { en: 'Marivan', fa: 'مریوان', tr: 'Marivan' } },
  { code: 'IR-KURDISTAN-BANEH', provinceCode: 'IR-KURDISTAN', names: { en: 'Baneh', fa: 'بانه', tr: 'Baneh' } },
  { code: 'IR-KURDISTAN-BIJAR', provinceCode: 'IR-KURDISTAN', names: { en: 'Bijar', fa: 'بیجار', tr: 'Bicar' } },
  { code: 'IR-KURDISTAN-QORVEH', provinceCode: 'IR-KURDISTAN', names: { en: 'Qorveh', fa: 'قروه', tr: 'Korveh' } },
  { code: 'IR-KURDISTAN-KAMYARAN', provinceCode: 'IR-KURDISTAN', names: { en: 'Kamyaran', fa: 'کامیاران', tr: 'Kamyaran' } },
  { code: 'IR-KURDISTAN-DIVANDARREH', provinceCode: 'IR-KURDISTAN', names: { en: 'Divandarreh', fa: 'دیواندره', tr: 'Divandarreh' } },
  { code: 'IR-GILAN-RASHT', provinceCode: 'IR-GILAN', names: { en: 'Rasht', fa: 'رشت', tr: 'Raşt' } },
  { code: 'IR-GILAN-BANDAR_E_ANZALI', provinceCode: 'IR-GILAN', names: { en: 'Bandar-e Anzali', fa: 'بندر انزلی', tr: 'Bandar-e Anzali' } },
  { code: 'IR-GILAN-LAHIJAN', provinceCode: 'IR-GILAN', names: { en: 'Lahijan', fa: 'لاهیجان', tr: 'Lahican' } },
  { code: 'IR-GILAN-LANGARUD', provinceCode: 'IR-GILAN', names: { en: 'Langarud', fa: 'لنگرود', tr: 'Langarud' } },
  { code: 'IR-GILAN-ASTARA', provinceCode: 'IR-GILAN', names: { en: 'Astara', fa: 'آستارا', tr: 'Astara' } },
  { code: 'IR-GILAN-TALESH', provinceCode: 'IR-GILAN', names: { en: 'Talesh', fa: 'تالش', tr: 'Taleş' } },
  { code: 'IR-GILAN-FUMAN', provinceCode: 'IR-GILAN', names: { en: 'Fuman', fa: 'فومن', tr: 'Fuman' } },
  { code: 'IR-GILAN-RUDSAR', provinceCode: 'IR-GILAN', names: { en: 'Rudsar', fa: 'رودسر', tr: 'Rudsar' } },
  { code: 'IR-GILAN-ASTANEH_YE_ASHRAFIYEH', provinceCode: 'IR-GILAN', names: { en: 'Astaneh-ye Ashrafiyeh', fa: 'آستانه اشرفیه', tr: 'Astaneh-ye Aşrafiyeh' } },
  { code: 'IR-GILAN-ROUDBAR', provinceCode: 'IR-GILAN', names: { en: 'Roudbar', fa: 'رودبار', tr: 'Roudbar' } },
  { code: 'IR-GILAN-SOWME_EH_SARA', provinceCode: 'IR-GILAN', names: { en: 'Sowme\'eh Sara', fa: 'صومعه‌سرا', tr: 'Sovme\'eh Sara' } },
  { code: 'IR-MAZANDARAN-SARI', provinceCode: 'IR-MAZANDARAN', names: { en: 'Sari', fa: 'ساری', tr: 'Sari' } },
  { code: 'IR-MAZANDARAN-BABOL', provinceCode: 'IR-MAZANDARAN', names: { en: 'Babol', fa: 'بابل', tr: 'Babol' } },
  { code: 'IR-MAZANDARAN-AMOL', provinceCode: 'IR-MAZANDARAN', names: { en: 'Amol', fa: 'آمل', tr: 'Amol' } },
  { code: 'IR-MAZANDARAN-QAEM_SHAHR', provinceCode: 'IR-MAZANDARAN', names: { en: 'Qaem Shahr', fa: 'قائم‌شهر', tr: 'Kaem Şahr' } },
  { code: 'IR-MAZANDARAN-BEHSHAHR', provinceCode: 'IR-MAZANDARAN', names: { en: 'Behshahr', fa: 'بهشهر', tr: 'Behşahr' } },
  { code: 'IR-MAZANDARAN-CHALUS', provinceCode: 'IR-MAZANDARAN', names: { en: 'Chalus', fa: 'چالوس', tr: 'Çalus' } },
  { code: 'IR-MAZANDARAN-NOWSHAHR', provinceCode: 'IR-MAZANDARAN', names: { en: 'Nowshahr', fa: 'نوشهر', tr: 'Novşahr' } },
  { code: 'IR-MAZANDARAN-RAMSAR', provinceCode: 'IR-MAZANDARAN', names: { en: 'Ramsar', fa: 'رامسر', tr: 'Ramsar' } },
  { code: 'IR-MAZANDARAN-TONEKABON', provinceCode: 'IR-MAZANDARAN', names: { en: 'Tonekabon', fa: 'تنکابن', tr: 'Tonekabon' } },
  { code: 'IR-MAZANDARAN-BABOLSAR', provinceCode: 'IR-MAZANDARAN', names: { en: 'Babolsar', fa: 'بابلسر', tr: 'Babolsar' } },
  { code: 'IR-MAZANDARAN-JUYBAR', provinceCode: 'IR-MAZANDARAN', names: { en: 'Juybar', fa: 'جویبار', tr: 'Cuybar' } },
  { code: 'IR-MAZANDARAN-NUR', provinceCode: 'IR-MAZANDARAN', names: { en: 'Nur', fa: 'نور', tr: 'Nur' } },
  { code: 'IR-MAZANDARAN-FEREYDUNKENAR', provinceCode: 'IR-MAZANDARAN', names: { en: 'Fereydunkenar', fa: 'فریدونکنار', tr: 'Fereydunkenar' } },
  { code: 'IR-GOLESTAN-GORGAN', provinceCode: 'IR-GOLESTAN', names: { en: 'Gorgan', fa: 'گرگان', tr: 'Gorgan' } },
  { code: 'IR-GOLESTAN-GONBAD_E_KAVUS', provinceCode: 'IR-GOLESTAN', names: { en: 'Gonbad-e Kavus', fa: 'گنبد کاووس', tr: 'Gonbad-e Kavus' } },
  { code: 'IR-GOLESTAN-ALIABAD_E_KATUL', provinceCode: 'IR-GOLESTAN', names: { en: 'Aliabad-e Katul', fa: 'علی‌آباد کتول', tr: 'Aliabad-e Katul' } },
  { code: 'IR-GOLESTAN-KORDKUY', provinceCode: 'IR-GOLESTAN', names: { en: 'Kordkuy', fa: 'کردکوی', tr: 'Kordkuy' } },
  { code: 'IR-GOLESTAN-BANDAR_TORKAMAN', provinceCode: 'IR-GOLESTAN', names: { en: 'Bandar Torkaman', fa: 'بندر ترکمن', tr: 'Bandar Torkaman' } },
  { code: 'IR-GOLESTAN-AZADSHAHR', provinceCode: 'IR-GOLESTAN', names: { en: 'Azadshahr', fa: 'آزادشهر', tr: 'Azadşahr' } },
  { code: 'IR-GOLESTAN-MINOODASHT', provinceCode: 'IR-GOLESTAN', names: { en: 'Minoodasht', fa: 'مینودشت', tr: 'Minoodaşt' } },
  { code: 'IR-GOLESTAN-KALALEH', provinceCode: 'IR-GOLESTAN', names: { en: 'Kalaleh', fa: 'کلاله', tr: 'Kalaleh' } },
  { code: 'IR-SISTAN_BALUCHESTAN-ZAHEDAN', provinceCode: 'IR-SISTAN_BALUCHESTAN', names: { en: 'Zahedan', fa: 'زاهدان', tr: 'Zahedan' } },
  { code: 'IR-SISTAN_BALUCHESTAN-ZABOL', provinceCode: 'IR-SISTAN_BALUCHESTAN', names: { en: 'Zabol', fa: 'زابل', tr: 'Zabol' } },
  { code: 'IR-SISTAN_BALUCHESTAN-CHABAHAR', provinceCode: 'IR-SISTAN_BALUCHESTAN', names: { en: 'Chabahar', fa: 'چابهار', tr: 'Çabahar' } },
  { code: 'IR-SISTAN_BALUCHESTAN-IRANSHAHR', provinceCode: 'IR-SISTAN_BALUCHESTAN', names: { en: 'Iranshahr', fa: 'ایرانشهر', tr: 'Iranşahr' } },
  { code: 'IR-SISTAN_BALUCHESTAN-KHASH', provinceCode: 'IR-SISTAN_BALUCHESTAN', names: { en: 'Khash', fa: 'خاش', tr: 'Haş' } },
  { code: 'IR-SISTAN_BALUCHESTAN-SARAVAN', provinceCode: 'IR-SISTAN_BALUCHESTAN', names: { en: 'Saravan', fa: 'سراوان', tr: 'Saravan' } },
  { code: 'IR-SISTAN_BALUCHESTAN-KONARAK', provinceCode: 'IR-SISTAN_BALUCHESTAN', names: { en: 'Konarak', fa: 'کنارک', tr: 'Konarak' } },
  { code: 'IR-SISTAN_BALUCHESTAN-NIKSHAHR', provinceCode: 'IR-SISTAN_BALUCHESTAN', names: { en: 'Nikshahr', fa: 'نیک‌شهر', tr: 'Nikşahr' } },
  { code: 'IR-HORMOZGAN-BANDAR_ABBAS', provinceCode: 'IR-HORMOZGAN', names: { en: 'Bandar Abbas', fa: 'بندرعباس', tr: 'Bandar Abbas' } },
  { code: 'IR-HORMOZGAN-MINAB', provinceCode: 'IR-HORMOZGAN', names: { en: 'Minab', fa: 'میناب', tr: 'Minab' } },
  { code: 'IR-HORMOZGAN-QESHM', provinceCode: 'IR-HORMOZGAN', names: { en: 'Qeshm', fa: 'قشم', tr: 'Keşm' } },
  { code: 'IR-HORMOZGAN-BANDAR_LENGEH', provinceCode: 'IR-HORMOZGAN', names: { en: 'Bandar Lengeh', fa: 'بندر لنگه', tr: 'Bandar Lengeh' } },
  { code: 'IR-HORMOZGAN-RUDAN', provinceCode: 'IR-HORMOZGAN', names: { en: 'Rudan', fa: 'رودان', tr: 'Rudan' } },
  { code: 'IR-HORMOZGAN-KISH', provinceCode: 'IR-HORMOZGAN', names: { en: 'Kish', fa: 'کیش', tr: 'Kiş' } },
  { code: 'IR-HORMOZGAN-BASTAK', provinceCode: 'IR-HORMOZGAN', names: { en: 'Bastak', fa: 'بستک', tr: 'Bastak' } },
  { code: 'IR-HORMOZGAN-JASK', provinceCode: 'IR-HORMOZGAN', names: { en: 'Jask', fa: 'جاسک', tr: 'Cask' } },
  { code: 'IR-BUSHEHR-BUSHEHR', provinceCode: 'IR-BUSHEHR', names: { en: 'Bushehr', fa: 'بوشهر', tr: 'Buşehr' } },
  { code: 'IR-BUSHEHR-BORAZJAN', provinceCode: 'IR-BUSHEHR', names: { en: 'Borazjan', fa: 'برازجان', tr: 'Borazcan' } },
  { code: 'IR-BUSHEHR-GENAVEH', provinceCode: 'IR-BUSHEHR', names: { en: 'Genaveh', fa: 'گناوه', tr: 'Genaveh' } },
  { code: 'IR-BUSHEHR-KANGAN', provinceCode: 'IR-BUSHEHR', names: { en: 'Kangan', fa: 'کنگان', tr: 'Kangan' } },
  { code: 'IR-BUSHEHR-AHRAM', provinceCode: 'IR-BUSHEHR', names: { en: 'Ahram', fa: 'اهرم', tr: 'Ahram' } },
  { code: 'IR-BUSHEHR-DAYYER', provinceCode: 'IR-BUSHEHR', names: { en: 'Dayyer', fa: 'دیر', tr: 'Dayyer' } },
  { code: 'IR-BUSHEHR-DEYLAM', provinceCode: 'IR-BUSHEHR', names: { en: 'Deylam', fa: 'دیلم', tr: 'Deylam' } },
  { code: 'IR-YAZD-YAZD', provinceCode: 'IR-YAZD', names: { en: 'Yazd', fa: 'یزد', tr: 'Yezd' } },
  { code: 'IR-YAZD-MEYBOD', provinceCode: 'IR-YAZD', names: { en: 'Meybod', fa: 'میبد', tr: 'Meybod' } },
  { code: 'IR-YAZD-ARDAKAN', provinceCode: 'IR-YAZD', names: { en: 'Ardakan', fa: 'اردکان', tr: 'Ardakan' } },
  { code: 'IR-YAZD-BAFQ', provinceCode: 'IR-YAZD', names: { en: 'Bafq', fa: 'بافق', tr: 'Bafk' } },
  { code: 'IR-YAZD-ABARKUH', provinceCode: 'IR-YAZD', names: { en: 'Abarkuh', fa: 'ابرکوه', tr: 'Abarkuh' } },
  { code: 'IR-YAZD-TAFT', provinceCode: 'IR-YAZD', names: { en: 'Taft', fa: 'تفت', tr: 'Taft' } },
  { code: 'IR-YAZD-MEHRIZ', provinceCode: 'IR-YAZD', names: { en: 'Mehriz', fa: 'مهریز', tr: 'Mehriz' } },
  { code: 'IR-SEMNAN-SEMNAN', provinceCode: 'IR-SEMNAN', names: { en: 'Semnan', fa: 'سمنان', tr: 'Semnan' } },
  { code: 'IR-SEMNAN-SHAHRUD', provinceCode: 'IR-SEMNAN', names: { en: 'Shahrud', fa: 'شاهرود', tr: 'Şahrud' } },
  { code: 'IR-SEMNAN-DAMGHAN', provinceCode: 'IR-SEMNAN', names: { en: 'Damghan', fa: 'دامغان', tr: 'Damğan' } },
  { code: 'IR-SEMNAN-GARMSAR', provinceCode: 'IR-SEMNAN', names: { en: 'Garmsar', fa: 'گرمسار', tr: 'Garmsar' } },
  { code: 'IR-SEMNAN-SORKHEH', provinceCode: 'IR-SEMNAN', names: { en: 'Sorkheh', fa: 'سرخه', tr: 'Sorheh' } },
  { code: 'IR-SEMNAN-MAHDISHAHR', provinceCode: 'IR-SEMNAN', names: { en: 'Mahdishahr', fa: 'مهدی‌شهر', tr: 'Mahdişahr' } },
  { code: 'IR-QOM-QOM', provinceCode: 'IR-QOM', names: { en: 'Qom', fa: 'قم', tr: 'Kum' } },
  { code: 'IR-QOM-KAHAK', provinceCode: 'IR-QOM', names: { en: 'Kahak', fa: 'کهک', tr: 'Kahak' } },
  { code: 'IR-QOM-JAFARIYEH', provinceCode: 'IR-QOM', names: { en: 'Jafariyeh', fa: 'جعفریه', tr: 'Cafariyeh' } },
  { code: 'IR-QAZVIN-QAZVIN', provinceCode: 'IR-QAZVIN', names: { en: 'Qazvin', fa: 'قزوین', tr: 'Kazvin' } },
  { code: 'IR-QAZVIN-TAKESTAN', provinceCode: 'IR-QAZVIN', names: { en: 'Takestan', fa: 'تاکستان', tr: 'Takestan' } },
  { code: 'IR-QAZVIN-ABYEK', provinceCode: 'IR-QAZVIN', names: { en: 'Abyek', fa: 'آبیک', tr: 'Abyek' } },
  { code: 'IR-QAZVIN-ALVAND', provinceCode: 'IR-QAZVIN', names: { en: 'Alvand', fa: 'الوند', tr: 'Alvand' } },
  { code: 'IR-QAZVIN-BUIN_ZAHRA', provinceCode: 'IR-QAZVIN', names: { en: 'Buin Zahra', fa: 'بوئین زهرا', tr: 'Buin Zahra' } },
  { code: 'IR-ZANJAN-ZANJAN', provinceCode: 'IR-ZANJAN', names: { en: 'Zanjan', fa: 'زنجان', tr: 'Zencan' } },
  { code: 'IR-ZANJAN-ABHAR', provinceCode: 'IR-ZANJAN', names: { en: 'Abhar', fa: 'ابهر', tr: 'Abhar' } },
  { code: 'IR-ZANJAN-KHORRAMDARREH', provinceCode: 'IR-ZANJAN', names: { en: 'Khorramdarreh', fa: 'خرمدره', tr: 'Horramdarreh' } },
  { code: 'IR-ZANJAN-MAHNESHAN', provinceCode: 'IR-ZANJAN', names: { en: 'Mahneshan', fa: 'ماه‌نشان', tr: 'Mahneşan' } },
  { code: 'IR-ZANJAN-TAROM', provinceCode: 'IR-ZANJAN', names: { en: 'Tarom', fa: 'طارم', tr: 'Tarom' } },
  { code: 'IR-ZANJAN-IJRUD', provinceCode: 'IR-ZANJAN', names: { en: 'Ijrud', fa: 'ایجرود', tr: 'Icrud' } },
  { code: 'IR-MARKAZI-ARAK', provinceCode: 'IR-MARKAZI', names: { en: 'Arak', fa: 'اراک', tr: 'Arak' } },
  { code: 'IR-MARKAZI-SAVEH', provinceCode: 'IR-MARKAZI', names: { en: 'Saveh', fa: 'ساوه', tr: 'Saveh' } },
  { code: 'IR-MARKAZI-KHOMEIN', provinceCode: 'IR-MARKAZI', names: { en: 'Khomein', fa: 'خمین', tr: 'Homein' } },
  { code: 'IR-MARKAZI-MAHALLAT', provinceCode: 'IR-MARKAZI', names: { en: 'Mahallat', fa: 'محلات', tr: 'Mahallat' } },
  { code: 'IR-MARKAZI-TAFRESH', provinceCode: 'IR-MARKAZI', names: { en: 'Tafresh', fa: 'تفرش', tr: 'Tafreş' } },
  { code: 'IR-MARKAZI-DELIJAN', provinceCode: 'IR-MARKAZI', names: { en: 'Delijan', fa: 'دلیجان', tr: 'Delican' } },
  { code: 'IR-MARKAZI-SHAZAND', provinceCode: 'IR-MARKAZI', names: { en: 'Shazand', fa: 'شازند', tr: 'Şazand' } },
  { code: 'IR-MARKAZI-ASHTIAN', provinceCode: 'IR-MARKAZI', names: { en: 'Ashtian', fa: 'آشتیان', tr: 'Aştian' } },
  { code: 'IR-HAMADAN-HAMADAN', provinceCode: 'IR-HAMADAN', names: { en: 'Hamadan', fa: 'همدان', tr: 'Hemedan' } },
  { code: 'IR-HAMADAN-MALAYER', provinceCode: 'IR-HAMADAN', names: { en: 'Malayer', fa: 'ملایر', tr: 'Malayer' } },
  { code: 'IR-HAMADAN-NAHAVAND', provinceCode: 'IR-HAMADAN', names: { en: 'Nahavand', fa: 'نهاوند', tr: 'Nahavand' } },
  { code: 'IR-HAMADAN-TUYSERKAN', provinceCode: 'IR-HAMADAN', names: { en: 'Tuyserkan', fa: 'تویسرکان', tr: 'Tuyserkan' } },
  { code: 'IR-HAMADAN-ASADABAD', provinceCode: 'IR-HAMADAN', names: { en: 'Asadabad', fa: 'اسدآباد', tr: 'Asadabad' } },
  { code: 'IR-HAMADAN-BAHAR', provinceCode: 'IR-HAMADAN', names: { en: 'Bahar', fa: 'بهار', tr: 'Bahar' } },
  { code: 'IR-HAMADAN-RAZAN', provinceCode: 'IR-HAMADAN', names: { en: 'Razan', fa: 'رزن', tr: 'Razan' } },
  { code: 'IR-HAMADAN-KABUDARAHANG', provinceCode: 'IR-HAMADAN', names: { en: 'Kabudarahang', fa: 'کبودراهنگ', tr: 'Kabudarahang' } },
  { code: 'IR-LORESTAN-KHORRAMABAD', provinceCode: 'IR-LORESTAN', names: { en: 'Khorramabad', fa: 'خرم‌آباد', tr: 'Horramabad' } },
  { code: 'IR-LORESTAN-BORUJERD', provinceCode: 'IR-LORESTAN', names: { en: 'Borujerd', fa: 'بروجرد', tr: 'Borucerd' } },
  { code: 'IR-LORESTAN-DORUD', provinceCode: 'IR-LORESTAN', names: { en: 'Dorud', fa: 'دورود', tr: 'Dorud' } },
  { code: 'IR-LORESTAN-ALIGUDARZ', provinceCode: 'IR-LORESTAN', names: { en: 'Aligudarz', fa: 'الیگودرز', tr: 'Aligudarz' } },
  { code: 'IR-LORESTAN-KUHDASHT', provinceCode: 'IR-LORESTAN', names: { en: 'Kuhdasht', fa: 'کوهدشت', tr: 'Kuhdaşt' } },
  { code: 'IR-LORESTAN-AZNA', provinceCode: 'IR-LORESTAN', names: { en: 'Azna', fa: 'ازنا', tr: 'Azna' } },
  { code: 'IR-LORESTAN-POLDOKHTAR', provinceCode: 'IR-LORESTAN', names: { en: 'Poldokhtar', fa: 'پل‌دختر', tr: 'Poldohtar' } },
  { code: 'IR-ILAM-ILAM', provinceCode: 'IR-ILAM', names: { en: 'Ilam', fa: 'ایلام', tr: 'İlam' } },
  { code: 'IR-ILAM-DEHLORAN', provinceCode: 'IR-ILAM', names: { en: 'Dehloran', fa: 'دهلران', tr: 'Dehloran' } },
  { code: 'IR-ILAM-ABDANAN', provinceCode: 'IR-ILAM', names: { en: 'Abdanan', fa: 'آبدانان', tr: 'Abdanan' } },
  { code: 'IR-ILAM-EYVAN', provinceCode: 'IR-ILAM', names: { en: 'Eyvan', fa: 'ایوان', tr: 'Eyvan' } },
  { code: 'IR-ILAM-MEHRAN', provinceCode: 'IR-ILAM', names: { en: 'Mehran', fa: 'مهران', tr: 'Mehran' } },
  { code: 'IR-ILAM-DAREH_SHAHR', provinceCode: 'IR-ILAM', names: { en: 'Dareh Shahr', fa: 'دره‌شهر', tr: 'Dareh Şahr' } },
  { code: 'IR-KOHGILUYEH_BOYERAHMAD-YASUJ', provinceCode: 'IR-KOHGILUYEH_BOYERAHMAD', names: { en: 'Yasuj', fa: 'یاسوج', tr: 'Yasuc' } },
  { code: 'IR-KOHGILUYEH_BOYERAHMAD-GACHSARAN', provinceCode: 'IR-KOHGILUYEH_BOYERAHMAD', names: { en: 'Gachsaran', fa: 'گچساران', tr: 'Gaçsaran' } },
  { code: 'IR-KOHGILUYEH_BOYERAHMAD-DEHDASHT', provinceCode: 'IR-KOHGILUYEH_BOYERAHMAD', names: { en: 'Dehdasht', fa: 'دهدشت', tr: 'Dehdaşt' } },
  { code: 'IR-KOHGILUYEH_BOYERAHMAD-SISAKHT', provinceCode: 'IR-KOHGILUYEH_BOYERAHMAD', names: { en: 'Sisakht', fa: 'سی‌سخت', tr: 'Sisaht' } },
  { code: 'IR-KOHGILUYEH_BOYERAHMAD-CHORAM', provinceCode: 'IR-KOHGILUYEH_BOYERAHMAD', names: { en: 'Choram', fa: 'چرام', tr: 'Çoram' } },
  { code: 'IR-CHAHARMAHAL_BAKHTIARI-SHAHREKORD', provinceCode: 'IR-CHAHARMAHAL_BAKHTIARI', names: { en: 'Shahrekord', fa: 'شهرکرد', tr: 'Şahrekord' } },
  { code: 'IR-CHAHARMAHAL_BAKHTIARI-FARSAN', provinceCode: 'IR-CHAHARMAHAL_BAKHTIARI', names: { en: 'Farsan', fa: 'فارسان', tr: 'Farsan' } },
  { code: 'IR-CHAHARMAHAL_BAKHTIARI-BROUJEN', provinceCode: 'IR-CHAHARMAHAL_BAKHTIARI', names: { en: 'Broujen', fa: 'بروجن', tr: 'Broucen' } },
  { code: 'IR-CHAHARMAHAL_BAKHTIARI-LORDEGAN', provinceCode: 'IR-CHAHARMAHAL_BAKHTIARI', names: { en: 'Lordegan', fa: 'لردگان', tr: 'Lordegan' } },
  { code: 'IR-CHAHARMAHAL_BAKHTIARI-ARDAL', provinceCode: 'IR-CHAHARMAHAL_BAKHTIARI', names: { en: 'Ardal', fa: 'اردل', tr: 'Ardal' } },
] as const;

const IRAN_CITY_CODES = new Set(IRAN_CITIES.map((c) => c.code));

/** True only when `cityCode` exists AND belongs to `provinceCode` — a
 * city code from a different province is rejected, not silently
 * accepted (per the Phase 2 task's explicit "do not silently repair an
 * invalid Province/City relationship" instruction). */
export function isValidIranCityForProvince(
  cityCode: unknown,
  provinceCode: string,
): cityCode is string {
  if (typeof cityCode !== 'string') return false;
  return IRAN_CITIES.some((c) => c.code === cityCode && c.provinceCode === provinceCode);
}

export function citiesForProvince(provinceCode: string): readonly CityOption[] {
  return IRAN_CITIES.filter((c) => c.provinceCode === provinceCode);
}

/** Existence check regardless of province — used to detect a value that
 * is a real Iranian city code (just possibly attached to the wrong
 * province, or to a non-Iran country), as opposed to garbage input. */
export function isValidIranCityCode(cityCode: unknown): cityCode is string {
  return typeof cityCode === 'string' && IRAN_CITY_CODES.has(cityCode);
}
